language: node_js

node_js:
- "node"

env:
  global:
  - GEMFURY_USER=base63
  # GEMFURY_API_KEY
  - secure: "RGwMWzL/KIt3cV2A/JYNQVwJBU8wjrCAKO4W/yc+rOAlOcQKv++fDv5kq6pdNiYTQkn0L8afbd38ISdYVqsiVxgwqhgfowHlJbplEPBNT4N9YaLai7AIFJRHL7ApP3SH2f3tABxusJfuTt2LIsOkIupYMKuf37ZK8gq3z6H8n3UJWWqyutF4H/DTmAuRsHBL+II2C9ifxuD5KiwJXFU8gTJ6E3RaWYkGepGf9+9ACEkBGPxaE/r2Kj2Wel5aovFWJgyOqOI6EikN24YrxxLPQiTe6h1JT6cASs6SFsoDi4Ye8Z1sVa8TPxuN5dRSQkMPCCNFK7zxmZzNCzcm8DuFv3EqZDXaJi3iyG6W5dKSlWpIx/KyULmYCAiZeSAMkUhkFaaINr+OJ8xblo8YGwE4wbWWQcRSsyUuYDcR1VYb1Tsx2ntBeYKhj7DH3Y/D+O/C0yH+bOKvyN6AWZSM+dcUMHhhqCQISj+ZAUKnnMeqd6JSt+dOUQw4Zyh835DyOqEnpznRoMDc8irDaNakU7wJlPQifyEEfYYnkS8nCnEJZL/uXrb+jg9VlV+riOMUkwb6dHBv3w2LePtw5Eb64Ae50u7931uH7rrqYskHYYyK9/qOCBLt0vP3p07uZkCpHp0+sIsDTN+xKQoBiJ3ak/dbzxMVUHK/UH9gPNuy163IPxo="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/togemfury --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
  on:
    tags: true
